databases:
 - name: mysite-qs9p
   databaseName: mysite_ot5p
   user: mysite

services:
 - type: web
   name: mysite-qs9p
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: mysite-qs9p
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false