databases:
 - name: mysite
   databaseName: mysite
   user: mysite

services:
 - type: web
   name: mysite
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: mysite
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false

  - type: pserv
    name: redis
    env: docker
    repo: https://github.com/render-examples/redis.git # optional
    envVars:
    - key: GENERATED_SECRET
      generateValue: true       # will generate a base64-encoded 256-bit secret
    - key: DASHBOARD_SECRET
      sync: false               # placeholder for a value to be added in the dashboard
    disk:
      name: redis-data
      mountPath: /var/lib/redis
      sizeGB: 10  